kind: pipeline
name: default
volumes: # 定义流水线挂载目录，用于共享数据
  - name: build_tmp #用于保存编译的文件
    host:
      path: /cargo # 从宿主机中挂载的目录
# clone:
#   disable: false
steps:
  - name: build
    image: thankrain/rust:1.0
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: build_tmp
        path: /drone/src/cargo #同步配置
    commands:
      - cd scripts && ./build.sh
      - ./deploy.sh